name: investsfree_app
description: A Flutter app for InvestsFree with Splash, Login, and Sign Up screens
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  provider: ^6.0.5
  shared_preferences: ^2.1.1
  google_fonts: ^4.0.3
  cupertino_icons: ^1.0.5
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true   # ✅ must be inside flutter
  assets:
    - assets/images/
